### ISSUE TITLE
メソッドの名前は何をするものなのかがわかる「動詞」にしよう

### ISSUE THREAD

**Issue by norotime** [aihara001/client_appli02#10]
https://github.com/aihara001/client_appli02/blob/b2b6b168f51db0e9d7c408a38610197beb065867/app/controllers/clients_controller.rb#L74

**Comment by aihara001** [comment]
修正しました。
修正前　session_client
修正後　access_permission
※メソッド命名ルールの意図をはき違えておりましたら申し訳ありません。
