### ISSUE TITLE
CRUD全部に対しての操作であればonlyオプションではない方が良さそうです

### ISSUE THREAD

**Issue by norotime** [aihara001/client_appli02#6]
https://github.com/aihara001/client_appli02/blob/b2b6b168f51db0e9d7c408a38610197beb065867/app/controllers/clients_controller.rb#L3

@aihara001 exceptを使う手もあります。

**Comment by aihara001** [comment]
修正しました
修正前　before_action :set_client_id, only: [:new, :create, :edit, :update, :destroy]
修正後　before_action :set_client_id, except: [:show]

**Comment by aihara001** [comment]
修正箇所が誤っていたので訂正いたします。
修正前　before_action :session_client, only: [:edit, :update, :destroy, :create, :new, :index]
修正後　before_action :session_client, except: [:show]

下記はもとに戻しました。
before_action :set_client_id, only: [:new, :create, :edit, :update, :destroy]
