### ISSUE TITLE
シンボルで書こう

### ISSUE THREAD

**Issue by norotime** [aihara001/client_appli02#7]
https://github.com/aihara001/client_appli02/blob/b2b6b168f51db0e9d7c408a38610197beb065867/app/controllers/clients_controller.rb#L23

https://docs.ruby-lang.org/ja/latest/class/Symbol.html

**Comment by aihara001** [comment]
修正しました
'new'　→　:new

**Comment by aihara001** [comment]
修正しました
'new'　→　:new　'edit'　→　:edit
